grpc:
  server:
    port: 9894
    reflection-service-enabled: true
    health-service-enabled: true
    shutdown-grace-period: 30
  client:
    user-service:
      address: 'static://localhost:9892'
      negotiationType: plaintext
    organization-service:
      address: 'static://localhost:9893'
      negotiationType: plaintext

spring:
  datasource:
    url: jdbc:h2:file:./apps/review/review
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        show-sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'
      settings:
        trace: true
        web-allow-others: true

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace

