server:
  port: 8181
  servlet:
    context-path: /auth

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        show-sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'
      settings:
        trace: true
        web-allow-others: true



logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace

rsa:
  key:
    privateKeyFile: 'src/main/resources/private_key.key'
    publicKeyFile: 'src/main/resources/public_key.pem'


token:
  header: 'Authorization'
  expiration: 3600
  refreshExpiration: 10000000