server:
  port: 8182
  servlet:
    context-path: /user


grpc:
  server:
    port: 9892
    reflection-service-enabled: true
    health-service-enabled: true
    shutdown-grace-period: 5



spring:
  datasource:
    url: jdbc:h2:mem:userdetails
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        show-sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'
      settings:
        trace: true
        web-allow-others: true

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace