package org.volunteered.apps.entity.enumeraion

enum class Country(val countryName: String) {
    AE("United Arab Emirates"),
    JO("Jordan"),
    SY("Syria"),
    HR("Croatia"),
    PA("Panama"),
    MT("Malta"),
    VE("Venezuela"),
    TW("Taiwan"),
    DK("Denmark"),
    PR("Puerto Rico"),
    VN("Vietnam"),
    US("United States"),
    ME("Montenegro"),
    SE("Sweden"),
    BO("Bolivia"),
    SG("Singapore"),
    BH("Bahrain"),
    SA("Saudi Arabia"),
    YE("Yemen"),
    IN("India"),
    FI("Finland"),
    BA("Bosnia and Herzegovina"),
    UA("Ukraine"),
    CH("Switzerland"),
    AR("Argentina"),
    EG("Egypt"),
    JP("Japan"),
    SV("El Salvador"),
    BR("Brazil"),
    IS("Iceland"),
    CZ("Czech Republic"),
    PL("Poland"),
    ES("Spain"),
    CS("Serbia and Montenegro"),
    MY("Malaysia"),
    CO("Colombia"),
    BG("Bulgaria"),
    PY("Paraguay"),
    EC("Ecuador"),
    SD("Sudan"),
    RO("Romania"),
    PH("Philippines"),
    TN("Tunisia"),
    GT("Guatemala"),
    KR("South Korea"),
    CY("Cyprus"),
    MX("Mexico"),
    RU("Russia"),
    HN("Honduras"),
    HK("Hong Kong"),
    NO("Norway"),
    HU("Hungary"),
    TH("Thailand"),
    IQ("Iraq"),
    CL("Chile"),
    MA("Morocco"),
    IE("Ireland"),
    TR("Turkey"),
    EE("Estonia"),
    QA("Qatar"),
    PT("Portugal"),
    LU("Luxembourg"),
    OM("Oman"),
    AL("Albania"),
    DO("Dominican Republic"),
    CU("Cuba"),
    NZ("New Zealand"),
    RS("Serbia"),
    UY("Uruguay"),
    GR("Greece"),
    IL("Israel"),
    ZA("South Africa"),
    FR("France"),
    AT("Austria"),
    AU("Australia"),
    NL("Netherlands"),
    CA("Canada"),
    LV("Latvia"),
    CR("Costa Rica"),
    KW("Kuwait"),
    LY("Libya"),
    DE("Germany"),
    DZ("Algeria"),
    SK("Slovakia"),
    LT("Lithuania"),
    IT("Italy"),
    BE("Belgium"),
    CN("China"),
    LB("Lebanon"),
    NI("Nicaragua"),
    MK("Macedonia"),
    BY("Belarus"),
    SI("Slovenia"),
    PE("Peru"),
    ID("Indonesia"),
    GB("United Kingdom"),
}
