name: Check

on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
env:
  CI: true

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check code quality
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Fetch develop branch
        run: git fetch origin develop:develop
      - name: Build affected modules
        uses: gradle/gradle-build-action@v2
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          gradle-version: 7.3
          arguments: runAffectedUnitTests -Paffected_module_detector.enable
